version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-174-129-227-205.compute-1.amazonaws.com
            port: '5432'
            database: d3m4sq7eav069g
            schema: schema.graphql
            user: wmrlwywkrexvmd
            password: cc4418e7ae7cf24c1fe998c5bbe033cf224d1fed28a0f1442bf3eb55c2ae39e5
            migrations: true